### ISSUE TITLE
github actions配置静态页面部署

### ISSUE THREAD

**Issue by laoyutong** [laoyutong/blog#16]
# github actions自动部署静态页面
## 实现目标
每次push代码的时候，自动打包并更新至github pages中
## 解决方案
- 添加github actions（.github/workflows/main.yml）
```yml
name: Deploy GitHub Pages
on:
  push:
    // 触发的推送分支
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      // 打包命令
      - name: Build
        run: npm install && npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          // 在developer setting中配置的 personal access tokens，需要包含workflow
          ACCESS_TOKEN: ${{ secrets.action_workflow }}
          // 目标分支，需要与github pages配置的分支一致
          BRANCH: gh-pages
          // 打包的目标文件目录
          FOLDER: dist

```
- `vite`项目配置文件
需要修改公共基础路径
```javascript
export default defineConfig({
  base: "./",
});

```
